[env:heltec-v2_1]
board_level = extra
;build_type = debug ; to make it possible to step through our jtag debugger 
extends = esp32_base
board = heltec_wifi_lora_32_V2
build_flags = 
  ${esp32_base.build_flags} -D HELTEC_V2_1 -I variants/heltec_v2.1
  -DGPS_POWER_TOGGLE ; comment this line to disable triple press function on the user button to turn off gps entirely.

# testy mx
  -DDEBUG_HEAP=1
  -DMESHTASTIC_EXCLUDE_WEBSERVER=1
  -DMAX_NUM_NODES=102
  -DOLED_PL=1
  -DMAX_RX_TOPHONE=8
  # w configuration.h  -DMINIMUM_SAFE_FREE_HEAP=8192
  
monitor_filters = esp32_exception_decoder, direct, log2file
